
import React, { useState } from 'react';
import { useLab } from '../contexts/LabContext';
import { 
  Settings, Plus, Search, MoreHorizontal, 
  Beaker, Activity, FileText, ChevronRight, X, Clock, DollarSign,
  Ruler, AlignCenter, Trash2, Edit
} from 'lucide-react';
import { TestDefinition, Department } from '../types';

const Departments: React.FC = () => {
  const { departments, addDepartment, addTest, updateTest, deleteTest, requests } = useLab();
  const [activeDeptId, setActiveDeptId] = useState(departments[0]?.id);
  const activeDept = departments.find(d => d.id === activeDeptId) || departments[0];

  // Modal States
  const [isDeptModalOpen, setIsDeptModalOpen] = useState(false);
  const [isTestModalOpen, setIsTestModalOpen] = useState(false);
  const [isEditingTest, setIsEditingTest] = useState(false);
  
  // Dropdown state for test actions
  const [activeTestDropdown, setActiveTestDropdown] = useState<string | null>(null);

  // Form States
  const [newDeptName, setNewDeptName] = useState('');
  const [testForm, setTestForm] = useState<Partial<TestDefinition>>({
    name: '',
    code: '',
    price: 0,
    tatHours: 24,
    unit: '',
    referenceRange: ''
  });

  const handleAddDepartment = (e: React.FormEvent) => {
    e.preventDefault();
    // ID is generated by LabContext to ensure uniqueness and audit trail
    addDepartment({
      name: newDeptName,
      testCount: 0,
      tests: []
    });
    setNewDeptName('');
    setIsDeptModalOpen(false);
  };

  const handleCreateOrUpdateTest = (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeDept) return;

    if (isEditingTest) {
        updateTest(activeDept.id, {
            ...testForm,
            departmentId: activeDept.id
        } as TestDefinition);
    } else {
        addTest(activeDept.id, {
            ...testForm,
            departmentId: activeDept.id
        } as TestDefinition);
    }

    closeTestModal();
  };

  const openAddTestModal = () => {
      setIsEditingTest(false);
      setTestForm({ name: '', code: '', price: 0, tatHours: 24, unit: '', referenceRange: '' });
      setIsTestModalOpen(true);
  };

  const openEditTestModal = (test: TestDefinition) => {
      setActiveTestDropdown(null);
      setIsEditingTest(true);
      setTestForm(test);
      setIsTestModalOpen(true);
  };

  const closeTestModal = () => {
      setIsTestModalOpen(false);
      setIsEditingTest(false);
  };

  const handleDeleteTest = (code: string) => {
      if (activeDept) {
          if (window.confirm(`Are you sure you want to delete test ${code}?`)) {
              deleteTest(activeDept.id, code);
              setActiveTestDropdown(null);
          }
      }
  };

  const pendingCount = requests.filter(r =>
    r.status !== 'Verified' &&
    r.status !== 'Published' &&
    r.status !== 'Rejected' &&
    r.analyses.some(a => activeDept?.tests.some(t => t.code === a.keyword))
  ).length;

  return (
    <div className="flex h-[calc(100vh-80px)] bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden -m-4">
      
      {/* Sidebar Navigation */}
      <div className="w-72 bg-slate-50 border-r border-slate-200 flex flex-col">
        <div className="p-6 border-b border-slate-200">
          <h2 className="font-black text-slate-900 text-lg tracking-tight">Configuration</h2>
          <p className="text-xs text-slate-500 font-medium mt-1">Laboratory catalogues & ranges</p>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-1">
          <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest px-2 mb-2 mt-2">Departments</div>
          {departments.map(dept => (
            <button
              key={dept.id}
              onClick={() => setActiveDeptId(dept.id)}
              className={`w-full text-left px-3 py-2.5 rounded-lg text-sm font-medium flex items-center justify-between transition-all group ${
                activeDeptId === dept.id 
                ? 'bg-white text-blue-600 shadow-sm ring-1 ring-slate-200' 
                : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
              }`}
            >
              <div className="flex items-center gap-3">
                 <div className={`w-2 h-2 rounded-full ${activeDeptId === dept.id ? 'bg-blue-600' : 'bg-slate-300 group-hover:bg-slate-400'}`}></div>
                 {dept.name}
              </div>
              {activeDeptId === dept.id && <ChevronRight size={14} />}
            </button>
          ))}

          <button 
            onClick={() => setIsDeptModalOpen(true)}
            className="w-full mt-4 flex items-center gap-2 px-3 py-2 text-xs font-bold text-slate-500 hover:text-blue-600 transition-colors border-t border-slate-200 pt-4"
          >
             <Plus size={14} /> Add New Department
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-w-0 bg-white" onClick={() => setActiveTestDropdown(null)}>
        {/* Header */}
        <div className="px-8 py-6 border-b border-slate-100 flex justify-between items-start">
           <div>
             <div className="flex items-center gap-2 mb-1">
                <span className="px-2 py-0.5 rounded text-[10px] font-black bg-slate-100 text-slate-500 uppercase">{activeDept?.id}</span>
                <h1 className="text-xl font-bold text-slate-900">{activeDept?.name}</h1>
             </div>
             <p className="text-sm text-slate-500">Manage {activeDept?.testCount} investigation protocols and pricing.</p>
           </div>
           <div className="flex gap-2">
              <button 
                onClick={openAddTestModal}
                className="px-4 py-2 bg-slate-900 text-white rounded-lg text-sm font-bold shadow-lg hover:bg-slate-800 transition-all flex items-center gap-2"
              >
                 <Plus size={16} /> Add Test
              </button>
           </div>
        </div>

        {/* Stats Bar */}
        <div className="grid grid-cols-4 border-b border-slate-100 bg-slate-50/50">
           <div className="p-4 border-r border-slate-100">
              <div className="text-xs text-slate-500 font-medium mb-1">Total Tests</div>
              <div className="text-lg font-black text-slate-900">{activeDept?.tests.length}</div>
           </div>
           <div className="p-4 border-r border-slate-100">
              <div className="text-xs text-slate-500 font-medium mb-1">Avg. Price</div>
              <div className="text-lg font-black text-slate-900">Rs. {Math.round(activeDept?.tests.reduce((acc, t) => acc + t.price, 0) / (activeDept?.tests.length || 1))}</div>
           </div>
           <div className="p-4 border-r border-slate-100">
              <div className="text-xs text-slate-500 font-medium mb-1">Pending Results</div>
              <div className={`text-lg font-black ${pendingCount > 0 ? 'text-orange-600' : 'text-slate-900'}`}>{pendingCount}</div>
           </div>
           <div className="p-4">
              <div className="text-xs text-slate-500 font-medium mb-1">Status</div>
              <div className="flex items-center gap-1.5 text-green-600 text-xs font-bold uppercase">
                 <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div> Active
              </div>
           </div>
        </div>

        {/* Test List Table */}
        <div className="flex-1 overflow-y-auto">
           <table className="w-full text-left">
              <thead className="sticky top-0 bg-white border-b border-slate-100 z-10">
                 <tr>
                    <th className="px-8 py-3 text-xs font-bold text-slate-500 uppercase bg-slate-50/50">Test Name</th>
                    <th className="px-8 py-3 text-xs font-bold text-slate-500 uppercase bg-slate-50/50">Code</th>
                    <th className="px-8 py-3 text-xs font-bold text-slate-500 uppercase bg-slate-50/50">Reference</th>
                    <th className="px-8 py-3 text-xs font-bold text-slate-500 uppercase bg-slate-50/50">Price</th>
                    <th className="px-8 py-3 text-xs font-bold text-slate-500 uppercase bg-slate-50/50 w-16"></th>
                 </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                 {activeDept?.tests.map(test => (
                    <tr key={test.code} className="hover:bg-blue-50/50 group transition-colors relative">
                       <td className="px-8 py-4">
                          <div className="flex items-center gap-3">
                             <div className="w-8 h-8 rounded bg-slate-100 flex items-center justify-center text-slate-500 group-hover:bg-blue-100 group-hover:text-blue-600 transition-colors">
                                <Beaker size={16} />
                             </div>
                             <span className="text-sm font-bold text-slate-900">{test.name}</span>
                          </div>
                       </td>
                       <td className="px-8 py-4">
                          <span className="font-mono text-xs font-bold text-slate-500 bg-slate-100 px-2 py-1 rounded">{test.code}</span>
                       </td>
                       <td className="px-8 py-4 text-sm text-slate-600 font-medium">
                          <div className="flex items-center gap-2">
                              {test.referenceRange ? (
                                <>
                                    <span className="text-slate-900">{test.referenceRange}</span>
                                    <span className="text-xs text-slate-400 font-bold">{test.unit}</span>
                                </>
                              ) : (
                                <span className="text-slate-400 italic">Not defined</span>
                              )}
                          </div>
                       </td>
                       <td className="px-8 py-4">
                          <span className="text-sm font-bold text-slate-900">Rs. {test.price.toLocaleString()}</span>
                       </td>
                       <td className="px-8 py-4 text-right">
                          <div className="relative">
                              <button 
                                onClick={(e) => { e.stopPropagation(); setActiveTestDropdown(activeTestDropdown === test.code ? null : test.code); }}
                                className="text-slate-300 hover:text-blue-600 transition-colors p-1"
                              >
                                 <MoreHorizontal size={18} />
                              </button>
                              {activeTestDropdown === test.code && (
                                  <div className="absolute right-0 top-full mt-1 bg-white border border-slate-200 rounded-lg shadow-xl z-20 w-32 py-1">
                                      <button 
                                        onClick={() => openEditTestModal(test)}
                                        className="w-full text-left px-3 py-2 text-xs font-bold text-blue-600 hover:bg-blue-50 flex items-center gap-2"
                                      >
                                          <Edit size={12} /> Edit
                                      </button>
                                      <button 
                                        onClick={() => handleDeleteTest(test.code)}
                                        className="w-full text-left px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50 flex items-center gap-2"
                                      >
                                          <Trash2 size={12} /> Remove
                                      </button>
                                  </div>
                              )}
                          </div>
                       </td>
                    </tr>
                 ))}
              </tbody>
           </table>
        </div>
      </div>

      {/* Add Department Modal */}
      {isDeptModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-in fade-in">
           <div className="bg-white rounded-xl shadow-2xl w-full max-w-sm p-6">
              <div className="flex justify-between items-center mb-4">
                 <h3 className="font-bold text-slate-900">New Department</h3>
                 <button onClick={() => setIsDeptModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                    <X size={20} />
                 </button>
              </div>
              <form onSubmit={handleAddDepartment}>
                 <div className="space-y-4">
                    <div>
                       <label className="text-xs font-bold text-slate-500 uppercase">Department Name</label>
                       <input 
                         autoFocus
                         className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                         placeholder="e.g. Molecular Biology"
                         value={newDeptName}
                         onChange={e => setNewDeptName(e.target.value)}
                         required
                       />
                    </div>
                    <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2.5 rounded-lg shadow-lg shadow-blue-200 transition-all">
                       Create Department
                    </button>
                 </div>
              </form>
           </div>
        </div>
      )}

      {/* Add/Edit Test Modal */}
      {isTestModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-in fade-in">
           <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-6">
              <div className="flex justify-between items-center mb-4">
                 <h3 className="font-bold text-slate-900">{isEditingTest ? 'Edit Test' : `Add Test to ${activeDept?.name}`}</h3>
                 <button onClick={closeTestModal} className="text-slate-400 hover:text-slate-600">
                    <X size={20} />
                 </button>
              </div>
              <form onSubmit={handleCreateOrUpdateTest}>
                 <div className="space-y-4">
                    <div className="grid grid-cols-3 gap-4">
                        <div className="col-span-2">
                           <label className="text-xs font-bold text-slate-500 uppercase">Test Name</label>
                           <input 
                             autoFocus
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                             placeholder="e.g. PCR Covid-19"
                             value={testForm.name}
                             onChange={e => setTestForm({...testForm, name: e.target.value})}
                             required
                           />
                        </div>
                        <div>
                           <label className="text-xs font-bold text-slate-500 uppercase">Code</label>
                           <input 
                             disabled={isEditingTest}
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none font-mono uppercase disabled:bg-slate-50 disabled:text-slate-400"
                             placeholder="COV-19"
                             value={testForm.code}
                             onChange={e => setTestForm({...testForm, code: e.target.value})}
                             required
                           />
                        </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                        <div>
                           <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Ruler size={12}/> Unit</label>
                           <input 
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                             placeholder="e.g. mg/dL"
                             value={testForm.unit || ''}
                             onChange={e => setTestForm({...testForm, unit: e.target.value})}
                           />
                        </div>
                        <div>
                           <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><AlignCenter size={12}/> Ref. Range</label>
                           <input 
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                             placeholder="e.g. 10 - 20"
                             value={testForm.referenceRange || ''}
                             onChange={e => setTestForm({...testForm, referenceRange: e.target.value})}
                           />
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div>
                           <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><DollarSign size={12}/> Price (PKR)</label>
                           <input 
                             type="number"
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                             placeholder="0"
                             value={testForm.price || ''}
                             onChange={e => setTestForm({...testForm, price: parseFloat(e.target.value)})}
                             required
                           />
                        </div>
                        <div>
                           <label className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Clock size={12}/> TAT (Hours)</label>
                           <input 
                             type="number"
                             className="w-full mt-1 border border-slate-200 rounded-lg px-3 py-2 text-sm font-bold focus:ring-2 focus:ring-blue-500 outline-none"
                             placeholder="24"
                             value={testForm.tatHours || ''}
                             onChange={e => setTestForm({...testForm, tatHours: parseFloat(e.target.value)})}
                             required
                           />
                        </div>
                    </div>
                    <button className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-2.5 rounded-lg shadow-lg transition-all mt-2">
                       {isEditingTest ? 'Update Test' : 'Add Test Definition'}
                    </button>
                 </div>
              </form>
           </div>
        </div>
      )}
    </div>
  );
};

export default Departments;
